development:
  adapter: postgresql
  database: design_classics
  host: localhost
  min_messages: warning

test:
  adapter: postgresql
  database: design_classics
  host: localhost
  min_messages: warning