development:
  adapter: postgresql
  database: design_classics
  host: localhost
  min_messages: warning
  username: frankie

test:
  adapter: postgresql
  database: design_classics
  host: localhost
  min_messages: warning
  username: frankie
